name = "package-tracking"
main = "src/router.js"
compatibility_date = "2026-08-08"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "TRACKING_DB"
database_name = "package-tracking-db"
database_id = "2e43551b-bb2b-44d3-a93a-1f5fe0d89812"

[[services]]
binding = "TTG_AUTH"
service = "ttg-auth-api"

[vars]
GOOGLE_CLIENT_ID = "1070381167858-10im1vskjk3ppftpal9pq9j0bb6g5i44.apps.googleusercontent.com"
HANDOVER_SHEET_ID = "1KD4lu32bMWNlyKWohbNDQPivDEvVN-7_VcWq0Lj1OO4"
HANDOVER_SHEET_RANGE = "Handover Register!A:L"

[observability]
enabled = true

[triggers]
crons = ["*/15 * * * *"]
